runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index2.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*/)
  static_files: __static__\1index3.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index2.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index3.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /petition
  script: unused
  login: optional
  secure: optional
- url: /pquery
  script: unused
  login: optional
  secure: optional
- url: /hello
  script: unused
  login: optional
  secure: optional
- url: /getposts
  script: unused
  login: optional
  secure: optional
- url: /friends
  script: unused
  login: optional
  secure: optional
- url: /query
  script: unused
  login: optional
  secure: optional
- url: /fb
  script: unused
  login: optional
  secure: optional
- url: /counttr
  script: unused
  login: optional
  secure: optional
- url: /countsh
  script: unused
  login: optional
  secure: optional
- url: /count
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
